version: "1"
instances:
  - name: ubuntu
    type: amazon
    pool: 1    # total number of warm instances in the pool at all times
    limit: 100  # limit the total number of running servers. If exceeded block or error.
    platform:
      os: linux
      arch: amd64
    spec:
      account:
        region: us-east-2
        availability_zone: us-east-2c
        # access_key_id: 
        # access_key_secret:
        # key_pair_name:  # Key pair name.
      ami: ami-0fb653ca2d3203ac1
      size: t3.large
      # hibernate: true
      network:
        security_groups:
          - sg-0a4fdb1c324b5a8f8
  - name: windows
    type: amazon
    pool: 1     # total number of warm instances in the pool at all times
    limit: 100  # limit the total number of running servers. If exceeded block or error.
    platform:
      os: windows
      arch: amd64
    spec:
      account:
        region: us-east-2
        availability_zone: us-east-2c
        # access_key_id: 
        # access_key_secret:
        # key_pair_name:  # Key pair name.
      ami: ami-0133b0c98a20f9943
      size: t3.large
      # hibernate: true                               # Pool vms are hibernated after initialization if this flag is set.
      network:
        security_groups:
          - sg-0a4fdb1c324b5a8f8
        # subnet_id: subnet-0ab151a78e9307b           # Uncomment this line if subnet needs to be set
        # private_ip: true                            # Uncomment this line if public IP should not be allocated to the VM
      # disk:                                         # Uncomment disk section if disk size needs to be specified.
      #   size: 20                                    # Size of the volume in GBs